package org.cb.constants;

public class ErrorCodes {

    public static final String EC_REQUIRED_NOTIFICATION_USERS_ID = "EC_REQUIRED_NOTIFICATION_USERS_ID";

    public static final String EC_REQUIRED_NOTIFICATION_SUBJECT = "EC_REQUIRED_NOTIFICATION_SUBJECT";

    public static final String EC_REQUIRED_NOTIFICATION_USERNAME = "EC_REQUIRED_NOTIFICATION_USERNAME";

    public static final String EC_REQUIRED_NOTIFICATION_TOEMAIL = "EC_REQUIRED_NOTIFICATION_TOEMAIL";

    public static final String EC_INVALID_NOTIFICATION_EMAIL = "EC_INVALID_NOTIFICATION_EMAIL";

    public static final String EC_INVALID_INPUT = "EC_INVALID_INPUT";

}
